agent:
  algorithm: "RecurrentPPO"
  lr_actor: 0.0003
  lr_critic: 0.001
  gamma: 0.99
  K_epochs: 4
  eps_clip: 0.2
  update_timestep: 2000
  sequence_length: 8
  
sensory:
  using_sensory: true
  food_radius: 2
  danger_radius: 2

training:
  training_episode: 50000
  device: "auto"

environment:
  max_steps: 100
  danger_prob: 0.05
