# Default Configuration for GridWorld Interoceptive AI

environment:
  height: 5
  width: 5
  start_pos: [0, 0]
  food_pos: [4, 4]
  max_steps: 100

body:
  with_satiation: false
  max_satiation: 20
  start_satiation: 10
  random_start_satiation: true
  overeating_death: false  

agent:
  alpha: 0.1
  gamma: 0.99
  epsilon_start: 1.0
  epsilon_decay: 0.9995
  epsilon_min: 0.05

training:
  default_episodes: 100000
  seed: 46

testing:
  seed: 42
